services:
  jenkins:
    build: .                   
    container_name: devsecops-jenkins
    ports:
      - "8080:8080"            
      - "50000:50000"         
    volumes:
      - ../volumes/jenkins_home:/var/jenkins_home  

volumes:
  jenkins_home:                